### ISSUE TITLE
FYI: official Direct Line library

### ISSUE THREAD

**Issue by billba** [aravindkarnam/directline-api-v3#1]
Hi Aravind,

Just thought you'd like to know that I released an official Microsoft library for a similar purpose: https://github.com/microsoft/botframework-directlinejs

It's cool that we both did this with Observables. I'd be very interested in any feedback you might have to offer.

Thanks,
Bill

**Comment by aravindkarnam** [comment]
Thanks for reaching out to me bill. I started writing this project, because I was not able to find your library in the search I ran, when I started doing my project. I wanted to convert this into an angular app, so that I can use it across all my projects through directives. I will take a look at your library to possibly try and extend it into an angular app. I would really love to contribute in any way possible, so if you need an extra hand, please feel free to let me know. I wrote this to demonstrate my skills rather than to serve as a library for other developers. So i will include a link to your library in docs.   
Thanks,
Aravind

**Comment by billba** [comment]
That's great, and to be clear I wasn't trying to dissuade you from continuing with your project - the more the merrier!

Here's one tip - you don' need `request` - rxjs has its own Ajax library built-in.

**Comment by aravindkarnam** [comment]
Thanks for the tip bill. I will rewrite that.
